In [2]:
import torch
print(torch.__version__)  # 설치된 PyTorch 버전 출력
print(torch.cuda.is_available())  # CUDA 사용 가능 여부 확인

if torch.cuda.is_available():
    print(f"GPU 사용 가능: {torch.cuda.get_device_name(0)}")
else:
    print("GPU를 사용할 수 없습니다. CPU를 사용합니다.")

x = torch.rand(3, 3)
y = torch.rand(3, 3)
z = x + y
print("x:", x)
print("y:", y)
print("z:", z)

2.8.0+cpu
False
GPU를 사용할 수 없습니다. CPU를 사용합니다.
x: tensor([[0.4195, 0.1144, 0.3347],
        [0.6223, 0.1585, 0.5821],
        [0.6864, 0.6823, 0.9306]])
y: tensor([[0.0414, 0.8769, 0.5768],
        [0.1249, 0.3538, 0.2261],
        [0.7561, 0.7945, 0.4646]])
z: tensor([[0.4609, 0.9913, 0.9115],
        [0.7472, 0.5123, 0.8082],
        [1.4425, 1.4768, 1.3952]])


In [12]:
x = torch.ones(3, 3)  # 기존 텐서
print(x)
rand_tensor = torch.randint_like(x, 0, 10)  # 기존 크기 유지, 0~9 정수 샘플링

print(rand_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 2., 0.],
        [3., 7., 0.],
        [5., 1., 4.]])


In [18]:
tensor = torch.randperm(10)  # 0~9 정수를 무작위 섞기
print(tensor)

tensor([0, 2, 3, 9, 7, 1, 6, 4, 5, 8])


In [31]:
probs = torch.tensor([0.2, 0.8, 0.5, 0.9])  # 0~1 사이 확률값

tensor = torch.bernoulli(probs)  # 각 확률에 따라 0 또는 1 생성

print(tensor)

tensor([0., 1., 0., 1.])


In [41]:
probs = torch.tensor([0.1, 0.2, 0.3, 0.4])  # 각 요소의 선택 확률
tensor = torch.multinomial(probs, 2, replacement=True)  # 2개 선택 (복원 추출)
print(tensor)

tensor([3, 3])
